export const API_MOUNTS = {
    AUTH: "/api/auth",
    USER: "/api/user",
    TRAINER: "/api/trainer",
    ADMIN: "/api/admin",
    CATEGORY: "/api/categories",
    SUBSCRIPTION: "/api/subscriptions",
    ONBOARDING: "/api/onboarding",
    EQUIPMENT: "/api/equipment",
    EXERCISE: "/api/exercises",
    TARGET_MUSCLE: "/api/target-muscles",
    MEAL_CATEGORY: "/api/meal-categories",
    HEALTH_LOG: "/api/user/health-log",
    DIET_PLAN: "/api/user/diet-plan",
    WORKOUT_PLAN: "/api/user/workout-plan",
    COACHING: "/api/coaching",
    BOOKING: "/api/booking",
    WALLET: "/api/wallet",
    NOTIFICATION: "/api/notifications",
    TRAINER_AVAILABILITY: "/api/availability",
    TRAINER_BOOKING_SETTINGS: "/api/booking-settings",
    VIDEO_CALL: "/api/video-sessions",
} as const;