export const TRAINER_PATHS = {
    TRAINERS: "/trainers",
    TRAINER_BY_ID: "/trainers/:profileId",
    PROFILE: "/profile",
    PROFILE_BY_ID: "/profile/:profileId",
    APPROVE_PROFILE: "/profile/:profileId/approve",
    REJECT_PROFILE: "/profile/:profileId/reject",
    PROFILE_STATUS: "/profile/status",
    PROFILE_UPDATE: "/profile",
    PROFILE_PICTURE: "/profile-picture",
    COVER_PHOTO: "/cover-photo",
    DOCUMENT: "/document",
    APPOINTMENTS: "/appointments",
    TOGGLE_TRAINER_STATUS: "/:id/toggle-status",
} as const;