import { WorkoutExerciseStatus, PlanType } from "../../../constants/fitness.constant";

export interface MarkDayCompletedDto {
  userId: string;
  planId: string;
  dayNumber: number;
  completed: boolean;
}

export interface MarkExerciseStatusDto {
  userId: string;
  planId: string;
  dayNumber: number;
  instanceId: string;
  status: WorkoutExerciseStatus;
}

export interface AiWorkoutExerciseDto {
  instanceId?: string;
  order: number;
  exerciseId: string;
  exerciseTitle?: string;
  targetMuscles?: string[];
  sets: number;
  reps?: number;
  durationSeconds?: number;
  estimatedDurationSeconds?: number;
  restSeconds: number;
  notes: string;
  status?: string;
  startedAt?: Date;
  timeTakenSeconds?: number;
}

export interface GenerateWorkoutDto {
  dayNumber: number;
  day: string;
  scheduledDate?: Date;
  type: "workout" | "rest";
  focus: string;
  estimatedDurationMinutes: number;
  status: string;
  completedAt?: Date;
  exercises: AiWorkoutExerciseDto[];
}

export interface WorkoutPlanDetailDto {
  workoutPlanId: string;
  days: GenerateWorkoutDto[];
  planType: PlanType;
}

export interface WorkoutPlanResponseDto extends WorkoutPlanDetailDto {
  weekNumber: number;
  startDate: Date;
  formattedStartDate?: string;
  endDate: Date;
  formattedEndDate?: string;
  status: string;
  autoGenerated?: boolean;
}

export interface CompletedHistoryItemDto {
  date: Date;
  planWeek: number;
  day: GenerateWorkoutDto;
}

export interface GetWorkoutPlansResponseDto {
  plans: WorkoutPlanResponseDto[];
  generationStatus: {
    canGenerate: boolean;
    isInactive: boolean;
    pendingDaysCount: number;
    hasCompletedWorkoutToday: boolean;
    firstPendingDayNumber: number;
  };
  isPremium?: boolean;
  completedHistory?: CompletedHistoryItemDto[];
}

export interface WorkoutTrendDataDto {
  label: string;
  completionRate: number;
}

export interface MuscleDistributionDto {
  muscleName: string;
  count: number;
  percentage: number;
}

export interface RecentActivityDto {
  scheduledDate: Date;
  dayName: string;
  status: string;
}

export interface ProgressBarDto {
  title: string;
  goalLabel: string;
  value: number;
  valueLabel: string;
}

export interface PieChartDto {
  labels: string[];
  values: number[];
}

export interface WorkoutProgressResponseDto {
  currentStreak: number;
  completionRate: number;
  workoutsCompleted: number;
  totalTrainingMinutes: number;

  progressBar: ProgressBarDto;
  pieChart: PieChartDto;

  trendData: WorkoutTrendDataDto[];
  muscleDistribution: MuscleDistributionDto[];
  recentActivities: RecentActivityDto[];
}

