import { WorkoutExerciseStatus } from "../../constants/fitness.constant";

export interface MarkDayCompletedDto {
  userId: string;
  planId: string;
  dayNumber: number;
  completed: boolean;
}

export interface MarkExerciseStatusDto {
  userId: string;
  planId: string;
  dayNumber: number;
  instanceId: string;
  status: WorkoutExerciseStatus;
}

export interface AiWorkoutExerciseDto {
  instanceId?: string;
  order: number;
  exerciseId: string;
  exerciseTitle?: string;
  targetMuscles?: string[];
  sets: number;
  reps?: number;
  durationSeconds?: number;
  estimatedDurationSeconds?: number;
  restSeconds: number;
  notes: string;
  status?: string;
  startedAt?: Date;
  timeTakenSeconds?: number;
}

export interface GenerateWorkoutDto {
  dayNumber: number;
  day: string;
  scheduledDate?: Date;
  type: "workout" | "rest";
  focus: string;
  estimatedDurationMinutes: number;
  status: string;
  completedAt?: Date;
  exercises: AiWorkoutExerciseDto[];
}

export interface WorkoutPlanDetailDto {
  workoutPlanId: string;
  days: GenerateWorkoutDto[];
  planType: 'general' | 'custom';
}

export interface WorkoutPlanResponseDto extends WorkoutPlanDetailDto {
  weekNumber: number;
  startDate: Date;
  formattedStartDate?: string;
  endDate: Date;
  formattedEndDate?: string;
  status: string;
  autoGenerated?: boolean;
}

export interface GetWorkoutPlansResponseDto {
  plans: WorkoutPlanResponseDto[];
  generationStatus: {
    canGenerate: boolean;
    isInactive: boolean;
    pendingDaysCount: number;
    hasCompletedWorkoutToday: boolean;
    firstPendingDayNumber: number;
  };
}

export interface WeeklyCompletionDto {
  weekNumber: number;
  completionRate: number;
}

export interface DailyCompletionDto {
  dayName: string;
  completionRate: number;
}

export interface MonthlyCompletionDto {
  monthName: string;
  completionRate: number;
}

export interface RecentActivityDto {
  scheduledDate: Date;
  dayName: string;
  status: string;
}

export interface MuscleDistributionDto {
  muscleName: string;
  count: number;
}

export interface WorkoutProgressResponseDto {
  currentStreak: number;
  completionRate: number;
  workoutsCompleted: number;
  totalTrainingMinutes: number;

  currentWeekProgress: number;
  todayWorkoutProgress: number;

  plannedWorkouts: number;
  completedWorkouts: number;
  skippedWorkouts: number;

  weeklyCompletionTrend: WeeklyCompletionDto[];
  dailyCompletionTrend: DailyCompletionDto[];
  monthlyCompletionTrend: MonthlyCompletionDto[];
  muscleDistribution: MuscleDistributionDto[];
  recentActivities: RecentActivityDto[];
}
