export const VIDEO_SESSION_TERMINATION_REASON = {
  USER_NO_SHOW: "USER_NO_SHOW",
  TRAINER_NO_SHOW: "TRAINER_NO_SHOW",
  BOTH_NO_SHOW: "BOTH_NO_SHOW",

  USER_REJECTED: "USER_REJECTED",

  USER_DISCONNECTED: "USER_DISCONNECTED",
  TRAINER_DISCONNECTED: "TRAINER_DISCONNECTED",

  USER_ENDED: "USER_ENDED",
  TRAINER_ENDED: "TRAINER_ENDED",

  TECHNICAL_FAILURE: "TECHNICAL_FAILURE",
  SYSTEM_FAILURE: "SYSTEM_FAILURE",

  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  SCHEDULE_ENDED: "SCHEDULE_ENDED",
} as const;

export type VideoSessionTerminationReason =
  (typeof VIDEO_SESSION_TERMINATION_REASON)[keyof typeof VIDEO_SESSION_TERMINATION_REASON];


  export const VIDEO_SESSION_STATUS = {
  WAITING: "WAITING",
  ACCEPTED: "ACCEPTED",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
} as const;

export type VideoSessionStatus =
  (typeof VIDEO_SESSION_STATUS)[keyof typeof VIDEO_SESSION_STATUS];