export const NOTIFICATION_TYPE = {
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  NEW_BOOKING_RECEIVED: "NEW_BOOKING_RECEIVED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_REJECTED: "BOOKING_REJECTED",

  RESCHEDULE_PROPOSED: "RESCHEDULE_PROPOSED",
  RESCHEDULE_REQUEST_RECEIVED: "RESCHEDULE_REQUEST_RECEIVED",
  RESCHEDULE_ACCEPTED: "RESCHEDULE_ACCEPTED",
  RESCHEDULE_REJECTED: "RESCHEDULE_REJECTED",

  SESSION_REMINDER: "SESSION_REMINDER",
  SESSION_STARTING_SOON: "SESSION_STARTING_SOON",

  PAYMENT_SUCCESSFUL: "PAYMENT_SUCCESSFUL",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_ISSUE: "PAYMENT_ISSUE",

  SUBSCRIPTION_PURCHASED: "SUBSCRIPTION_PURCHASED",
  SUBSCRIPTION_RENEWED: "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_EXPIRING_SOON: "SUBSCRIPTION_EXPIRING_SOON",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",

  TRAINER_APPLICATION_SUBMITTED: "TRAINER_APPLICATION_SUBMITTED",
  TRAINER_APPROVED: "TRAINER_APPROVED",
  TRAINER_REJECTED: "TRAINER_REJECTED",
  TRAINER_PROFILE_UPDATE_REQUIRED: "TRAINER_PROFILE_UPDATE_REQUIRED",
  NEW_TRAINER_APPLICATION: "NEW_TRAINER_APPLICATION",

  REFUND_PROCESSED: "REFUND_PROCESSED",
  REFUND_REQUIRES_PROCESSING: "REFUND_REQUIRES_PROCESSING",

  WALLET_CREDITED: "WALLET_CREDITED",
  WALLET_PAYMENT_SUCCESSFUL: "WALLET_PAYMENT_SUCCESSFUL",

  WORKOUT_PLAN_GENERATED: "WORKOUT_PLAN_GENERATED",
  NEW_WORKOUT_ASSIGNED: "NEW_WORKOUT_ASSIGNED",
  WORKOUT_PLAN_UPDATED: "WORKOUT_PLAN_UPDATED",
  WORKOUT_REMINDER: "WORKOUT_REMINDER",
  WORKOUT_MISSED: "WORKOUT_MISSED",
  WORKOUT_COMPLETED: "WORKOUT_COMPLETED",

  MEAL_PLAN_GENERATED: "MEAL_PLAN_GENERATED",
  MEAL_PLAN_UPDATED: "MEAL_PLAN_UPDATED",
  MEAL_REMINDER: "MEAL_REMINDER",

  DAILY_ROUTINE_REMINDER: "DAILY_ROUTINE_REMINDER",
  HYDRATION_REMINDER: "HYDRATION_REMINDER",
  SLEEP_REMINDER: "SLEEP_REMINDER",
  HEALTH_LOG_REMINDER: "HEALTH_LOG_REMINDER",

  RATING_REMINDER: "RATING_REMINDER",
  RATING_RECEIVED: "RATING_RECEIVED",
  FEEDBACK_RECEIVED: "FEEDBACK_RECEIVED",
  NEW_REVIEW: "NEW_REVIEW",

  NEW_MESSAGE: "NEW_MESSAGE",

  PAYOUT_PROCESSED: "PAYOUT_PROCESSED",
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];


  export const NOTIFICATION_ENTITY_TYPE = {
  BOOKING: "BOOKING",
  RESCHEDULE_REQUEST: "RESCHEDULE_REQUEST",
  REFUND: "REFUND",
  TRAINER: "TRAINER",
  REVIEW: "REVIEW",
  MESSAGE: "MESSAGE",
  PAYOUT: "PAYOUT",
  PAYMENT: "PAYMENT",
  SUBSCRIPTION: "SUBSCRIPTION",
  WORKOUT: "WORKOUT",
  MEAL_PLAN: "MEAL_PLAN",
  HEALTH_LOG: "HEALTH_LOG",
  WALLET: "WALLET",
  SYSTEM: "SYSTEM",
} as const;

export type NotificationEntityType =
  (typeof NOTIFICATION_ENTITY_TYPE)[keyof typeof NOTIFICATION_ENTITY_TYPE];