

export const VIDEO_SESSION_STATUS = {
    WAITING: "WAITING",
    ACCEPTED: "ACCEPTED",
    ACTIVE: "ACTIVE",
    COMPLETED: "COMPLETED",
    EXPIRED: "EXPIRED",
} as const;

export type VideoSessionStatus = (typeof VIDEO_SESSION_STATUS)[keyof typeof VIDEO_SESSION_STATUS];    


export const VIDEO_SESSION_TERMINATION_REASON = {
    SCHEDULE_ENDED: "SCHEDULE_ENDED",
    USER_NO_SHOW: "USER_NO_SHOW",
    TRAINER_NO_SHOW: "TRAINER_NO_SHOW",
    USER_REJECTED: "USER_REJECTED",
    TRAINER_CANCELED: "TRAINER_CANCELED",
    USER_CANCELED: "USER_CANCELED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    TRAINER_DISCONNECTED: "TRAINER_DISCONNECTED",
    SYSTEM_ERROR: "SYSTEM_ERROR",
} as const;


export type VideoSessionTerminationReason = (typeof VIDEO_SESSION_TERMINATION_REASON)[keyof typeof VIDEO_SESSION_TERMINATION_REASON];
